# Generated by Django 5.0.1 on 2024-01-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
