# Generated by Django 5.0.1 on 2024-01-12 12:13

from django.db import migrations


def popular_order(apps, schema_editor):
    Podcast = apps.get_model('podcasts', 'Podcast')
    for i, podcast in enumerate(Podcast.objects.order_by('data_gravacao').all()):
        podcast.order = i
        podcast.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_podcast_options_podcast_order'),
    ]

    operations = [
        migrations.RunPython(popular_order)
    ]
