services:

  database:
    container_name: engplat_db
    image: postgres:16.3
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=maindbpass
      - POSTGRES_USER=maindbuser
      - POSTGRES_DB=engpmaindb
    ports:
      - 5432:5432
