services:

  database:
    container_name: engplat_database
    image: postgres
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=maindbpass
      - POSTGRES_USER=maindbuser
      - POSTGRES_DB=maindb
    ports:
      - 5435:5432
