# Generated by Django 5.0.1 on 2024-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_altera_descr_modulo_e_cria_mod_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
